import "server-only";
import { absoluteUrl } from "@/lib/site";

type Copy={subject:string;eyebrow:string;headline:string;body:string;cta:string;path:string};
const templates:Record<string,Copy>={
  email_verification:{subject:"Verify your VendorDuel email",eyebrow:"Account security",headline:"Confirm it’s really you.",body:"Verify your business email to continue setting up your workspace.",cta:"Verify email",path:"/login"},
  duel_submitted:{subject:"Your Duel is in review",eyebrow:"Buyer update",headline:"Your spend is now leverage.",body:"The VendorDuel team will verify the submission before qualified vendors can challenge it.",cta:"View Duel",path:"/buyer"},
  duel_approved:{subject:"Your Duel is live",eyebrow:"Buyer update",headline:"The challengers can enter.",body:"Approved vendors that match your software and requirements can now submit sealed offers.",cta:"View live Duel",path:"/buyer"},
  new_challenge_received:{subject:"A new Challenge arrived",eyebrow:"Sealed offer",headline:"You have a new contender.",body:"A vendor submitted an independent offer. Commercial terms remain sealed until review begins.",cta:"Open buyer workspace",path:"/buyer/offers"},
  duel_ending_soon:{subject:"Your Duel closes soon",eyebrow:"Deadline",headline:"Final offers are approaching.",body:"Review your timeline. Submitted offers remain sealed until the Duel closes.",cta:"View Duel",path:"/buyer"},
  offers_ready:{subject:"Your offers are ready",eyebrow:"Compare",headline:"See who beat the deal.",body:"The Duel is closed and every submitted offer is now available in one structured comparison.",cta:"Compare offers",path:"/buyer/offers"},
  selection_confirmed:{subject:"Your vendor selection is confirmed",eyebrow:"Buyer update",headline:"You chose the conversation.",body:"The selected vendor has been invited to complete the fixed introduction payment.",cta:"Track introduction",path:"/buyer/introductions"},
  introduction_completed:{subject:"Your VendorDuel introduction is ready",eyebrow:"Introduction",headline:"The identities are unlocked.",body:"Payment was confirmed by Stripe and both sides can now contact one another directly.",cta:"Open introduction",path:"/buyer/introductions"},
  deal_confirmation:{subject:"How did the deal go?",eyebrow:"Follow-up",headline:"Confirm the outcome.",body:"Tell us whether the introduction produced a final agreement. Results stay private unless you separately consent to publication.",cta:"Confirm outcome",path:"/buyer/introductions"},
  vendor_approved:{subject:"Your vendor workspace is approved",eyebrow:"Vendor update",headline:"You’re cleared to compete.",body:"Browse qualified opportunities and submit sealed replacement offers.",cta:"Find Duels",path:"/vendor/opportunities"},
  matching_duel:{subject:"A matching Duel is live",eyebrow:"New opportunity",headline:"A buyer is challenging your competitor.",body:"The anonymized opportunity matches your registered replacement coverage.",cta:"View opportunity",path:"/vendor/opportunities"},
  challenge_submitted:{subject:"Your Challenge is locked",eyebrow:"Vendor update",headline:"Your offer is in.",body:"The commercial terms are versioned and no competing vendor can see them.",cta:"Track Challenge",path:"/vendor/challenges"},
  challenge_selected:{subject:"Your Challenge was selected",eyebrow:"You won",headline:"The buyer picked you.",body:"Complete the fixed introduction payment to unlock the buyer contact.",cta:"Complete payment",path:"/vendor/billing"},
  challenge_not_selected:{subject:"This buyer selected another offer",eyebrow:"Duel closed",headline:"Not this one.",body:"Your terms remain confidential. New matching opportunities will appear in your workspace.",cta:"Find another Duel",path:"/vendor/opportunities"},
  payment_receipt:{subject:"VendorDuel payment receipt",eyebrow:"Receipt",headline:"Introduction payment confirmed.",body:"Stripe confirmed the one-time introduction payment. Keep this message with your transaction records.",cta:"View billing",path:"/vendor/billing"},
  duel_closed:{subject:"A Duel you challenged has closed",eyebrow:"Duel closed",headline:"The buyer is reviewing.",body:"Offers are locked. We’ll notify you if the buyer selects your Challenge.",cta:"Track Challenges",path:"/vendor/challenges"},
  verification_required:{subject:"Buyer verification needs review",eyebrow:"Admin queue",headline:"A Duel needs a trust decision.",body:"Review the private evidence and record only the fields that were verified.",cta:"Review verification",path:"/admin/verifications"},
  vendor_awaiting_approval:{subject:"Vendor approval is waiting",eyebrow:"Admin queue",headline:"A vendor wants to compete.",body:"Review the organization, product coverage, and business contact before approval.",cta:"Review vendor",path:"/admin"},
  flagged_duel:{subject:"A Duel was flagged",eyebrow:"Admin alert",headline:"Marketplace review required.",body:"Check the report, public copy, verification state, and operator history.",cta:"Open reports",path:"/admin/reports"},
  payment_failed:{subject:"A VendorDuel payment failed",eyebrow:"Payment",headline:"The introduction is still locked.",body:"Stripe did not confirm payment. Retry checkout or use another payment method.",cta:"Return to billing",path:"/vendor/billing"},
  reported_vendor:{subject:"A vendor was reported",eyebrow:"Admin alert",headline:"Investigate marketplace conduct.",body:"A user submitted a vendor report. Review the evidence before taking action.",cta:"Open report queue",path:"/admin/reports"},
  data_request_received:{subject:"We received your privacy request",eyebrow:"Data rights",headline:"Your request is recorded.",body:"You can track its status in your privacy controls. Identity, legal retention, and third-party records may require review.",cta:"View privacy controls",path:"/account/privacy"}
};

const escape=(value:string)=>value.replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]!));
export function renderBrandedEmail(templateKey:string,payload:Record<string,unknown>={}){const copy=templates[templateKey]??{subject:"VendorDuel update",eyebrow:"Marketplace update",headline:"There’s an update in your workspace.",body:"Sign in to see the latest status.",cta:"Open VendorDuel",path:"/onboarding"};const reference=typeof payload.duel_id==="string"?` · Duel ${payload.duel_id.slice(0,8)}`:"";const url=absoluteUrl(copy.path);const html=`<!doctype html><html lang="en"><body style="margin:0;background:#f2f0e9;color:#171713;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${escape(copy.body)}</div><main style="max-width:640px;margin:0 auto;padding:40px 20px"><div style="background:#171713;color:#fffdf7;padding:28px"><b style="color:#d9ff43">V / VENDORDUEL</b></div><section style="background:#fffdf7;border:1px solid #171713;padding:42px 32px"><small style="font-weight:800;letter-spacing:.12em;text-transform:uppercase">${escape(copy.eyebrow)}${escape(reference)}</small><h1 style="font-size:44px;line-height:.95;letter-spacing:-.05em;margin:20px 0">${escape(copy.headline)}</h1><p style="color:#5b5a52;line-height:1.6">${escape(copy.body)}</p><a href="${url}" style="display:inline-block;margin-top:22px;padding:15px 20px;background:#171713;color:#fffdf7;text-decoration:none;font-weight:800">${escape(copy.cta)} →</a></section><p style="font-size:11px;line-height:1.5;color:#69685f">Transactional message from VendorDuel. Never send passwords or verification documents by email.</p></main></body></html>`;return {subject:copy.subject,html,text:`${copy.headline}\n\n${copy.body}\n\n${copy.cta}: ${url}`}}
