import type { Metadata } from "next";
import Link from "next/link";
import { requireOrganization } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { DashboardShell } from "@/components/dashboard-shell";
export const metadata: Metadata = { title: "Buyer introductions" }; export const dynamic = "force-dynamic";
export default async function BuyerIntroductionsPage() {
  const { organization } = await requireOrganization("buyer"); const supabase = await createClient(); const { data: introductions } = await supabase.from("introductions").select("id,status,vendor_organization_id,introduced_at,created_at").eq("buyer_organization_id", organization.organizationId).order("created_at", { ascending: false });
  const unlocked = (introductions ?? []).filter((item) => item.status === "paid" || item.status === "introduced"); const ids = unlocked.map((item) => item.vendor_organization_id);
  const [{ data: companies }, { data: profiles }] = ids.length ? await Promise.all([supabase.from("organizations").select("id,name,website_url").in("id", ids), supabase.from("vendor_profiles").select("organization_id,contact_name,contact_email").in("organization_id", ids)]) : [{ data: [] }, { data: [] }];
  return <DashboardShell area="Buyer" organization={organization.name}><div className="page-back"><Link href="/buyer">← Buyer dashboard</Link></div><div className="dashboard-heading"><div><span className="eyebrow">Introductions</span><h1>Selected conversations.</h1></div></div><div className="introduction-grid">{introductions?.map((intro) => { const company = companies?.find((item) => item.id === intro.vendor_organization_id); const profile = profiles?.find((item) => item.organization_id === intro.vendor_organization_id); const visible = intro.status === "paid" || intro.status === "introduced"; return <article className="introduction-card" key={intro.id}><span className={`badge badge-${intro.status}`}>{intro.status.replaceAll("_", " ")}</span><h2>{visible ? company?.name : "Selected vendor"}</h2>{visible ? <><p>{profile?.contact_name ?? "Vendor contact"}</p><a href={`mailto:${profile?.contact_email}`}>{profile?.contact_email}</a>{company?.website_url && <a href={company.website_url} target="_blank" rel="noreferrer">Visit website ↗</a>}</> : <p>The vendor is completing the introduction payment. Contact details unlock immediately afterward.</p>}</article>; })}{!introductions?.length && <div className="empty-panel"><h2>No introductions yet.</h2><p>Select a challenge after comparing offers.</p><Link href="/buyer/offers" className="button button-primary">View offers</Link></div>}</div></DashboardShell>;
}
