import type { Metadata } from "next";
import Link from "next/link";
import { requestAccountDeletion } from "@/app/actions/privacy";
import { requireIdentity } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import s from "../../legal.module.css";

export const metadata:Metadata={title:"Privacy controls"}; export const dynamic="force-dynamic";
export default async function AccountPrivacyPage(){const identity=await requireIdentity();const supabase=await createClient();const [{data:requests},{data:consents}]=await Promise.all([supabase.from("data_subject_requests").select("id,kind,status,requested_at,completed_at").eq("user_id",identity.id).order("requested_at",{ascending:false}),supabase.from("consent_records").select("id,purpose,policy_version,granted,recorded_at,withdrawn_at").eq("user_id",identity.id).order("recorded_at",{ascending:false})]);const pendingDeletion=requests?.some((r)=>r.kind==="deletion"&&["pending","processing"].includes(r.status));return <main className={s.page}><header className={s.header}><span className="eyebrow">Account privacy</span><h1>Control your data.</h1><p>Download a machine-readable copy or begin a reviewed deletion request. Some transaction and security records may need to be retained or anonymized.</p></header><section className={s.section}><h2>Export</h2><p>Your export contains account, workspace, Duel, offer, introduction, transaction, and consent records available to your identity.</p><div className={s.actions}><a className="button button-primary" href="/api/account/export">Download JSON export →</a><Link className="button button-secondary" href="/privacy">Read privacy policy</Link></div></section><section className={s.section}><h2>Delete account</h2>{pendingDeletion?<div className={s.notice}>Your deletion request is pending review. We will separate records that can be deleted from records subject to legal, fraud, payment, dispute, or security retention.</div>:<form className={s.request} action={requestAccountDeletion}><p>Deletion can remove workspace access and may prevent continued use of BeatMyVendor. Public Wins will be reviewed against their consent state.</p><label><span>Confirmation</span><span><input type="checkbox" name="acknowledge" value="yes" required/> I understand this request affects my account and workspaces.</span></label><button className="button button-secondary">Request deletion</button></form>}</section><section className={s.section}><h2>Request history</h2>{requests?.length?<ul>{requests.map((request)=><li key={request.id}>{request.kind} · {request.status} · {new Date(request.requested_at).toLocaleString("en")}</li>)}</ul>:<p>No formal data requests recorded.</p>}</section><section className={s.section}><h2>Consent receipts</h2>{consents?.length?<ul>{consents.map((consent)=><li key={consent.id}>{consent.purpose.replaceAll("_"," ")} · {consent.granted?"granted":"withdrawn"} · version {consent.policy_version} · {new Date(consent.recorded_at).toLocaleString("en")}</li>)}</ul>:<p>No optional consent has been recorded. Core service processing is not presented as consent.</p>}</section></main>}
