import type { Metadata } from "next";
import { moderateDuel } from "@/app/actions/admin-operations";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { AdminFrame } from "@/components/admin-frame";
import s from "../admin.module.css";

export const metadata: Metadata={title:"Duel moderation"}; export const dynamic="force-dynamic";
export default async function AdminDuelsPage(){await requireAdmin();const supabase=await createClient();const {data:duels}=await supabase.from("duels").select("id,public_id,status,annual_spend,currency,seats,country_code,submission_deadline,created_at,software_products!duels_current_software_product_id_fkey(name)").in("status",["pending_verification","open"]).order("created_at");return <AdminFrame><div className={s.navSpace}/><div className="dashboard-heading"><div><span className="eyebrow">Marketplace quality</span><h1>Duel moderation</h1></div><span className="badge">{duels?.length||0} active</span></div>{duels?.length?<div className={s.queue}>{duels.map((duel)=>{const product=Array.isArray(duel.software_products)?duel.software_products[0]:duel.software_products;return <article className={s.item} key={duel.id}><div><h2>VD-{duel.public_id} · {product?.name}</h2><p>{duel.country_code} · {duel.seats} seats · {duel.status.replaceAll("_"," ")}</p></div><div className={s.meta}><strong>{new Intl.NumberFormat("en",{style:"currency",currency:duel.currency,maximumFractionDigits:0}).format(Number(duel.annual_spend))}/year</strong><small>Deadline {duel.submission_deadline?new Date(duel.submission_deadline).toLocaleDateString("en"):"missing"}</small></div><div className={s.actions}><form action={moderateDuel}><input type="hidden" name="id" value={duel.id}/><input type="hidden" name="decision" value="rejected"/><input name="reason" required minLength={3} placeholder="Moderation reason"/><button className="button button-secondary">Reject</button></form>{duel.status==="pending_verification"&&<form action={moderateDuel}><input type="hidden" name="id" value={duel.id}/><input type="hidden" name="decision" value="open"/><button className="button button-primary">Publish</button></form>}</div></article>})}</div>:<div className={s.empty}>No Duels need moderation.</div>}</AdminFrame>}
