import type { Metadata } from "next";
import Link from "next/link";
import { requireOrganization } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { DashboardShell } from "@/components/dashboard-shell";
export const metadata: Metadata = { title: "Buyer offers" }; export const dynamic = "force-dynamic";
export default async function BuyerOffersPage() {
  const { organization } = await requireOrganization("buyer"); const supabase = await createClient();
  const { data: duels } = await supabase.from("duels").select("id,public_id,status,annual_spend,currency,submission_deadline,software_products(name),offers(id,status,annual_price)").eq("buyer_organization_id", organization.organizationId).in("status", ["open","reviewing","selected","introduced","converted","closed"]).order("created_at", { ascending: false });
  return <DashboardShell area="Buyer" organization={organization.name}><div className="page-back"><Link href="/buyer">← Buyer dashboard</Link></div><div className="dashboard-heading"><div><span className="eyebrow">Offer inbox</span><h1>Compare after the bell.</h1><p className="heading-copy">Offers remain sealed while submissions are open. When the deadline passes, every structured challenge appears together.</p></div></div><div className="duel-list">{duels?.map((duel) => { const product = Array.isArray(duel.software_products) ? duel.software_products[0] : duel.software_products; const offers = (duel.offers ?? []) as { id: string; status: string; annual_price: number }[]; const sealed = duel.status === "open" && new Date(duel.submission_deadline) > new Date(); return <Link className="duel-row" href={`/buyer/duels/${duel.id}/compare`} key={duel.id}><span className="duel-number">DUEL #{duel.public_id}</span><div><h2>{product?.name}</h2><p>{sealed ? "Offers sealed until deadline" : `${offers.length} challenge${offers.length === 1 ? "" : "s"} available`}</p></div><div className="duel-spend"><strong>{new Intl.NumberFormat("en", { style: "currency", currency: duel.currency, maximumFractionDigits: 0 }).format(Number(duel.annual_spend))}</strong><span>current spend</span></div><span className={`badge badge-${duel.status}`}>{duel.status.replaceAll("_", " ")}</span><span>→</span></Link>; })}{!duels?.length && <div className="empty-panel"><h2>No offer windows yet.</h2><p>Start a duel to invite structured vendor challenges.</p><Link className="button button-primary" href="/buyer/duels/new">Start a Duel</Link></div>}</div></DashboardShell>;
}
