import type { Metadata } from "next";
import { reviewDataRequest } from "@/app/actions/privacy-admin";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { AdminFrame } from "@/components/admin-frame";
import s from "../admin.module.css";

export const metadata:Metadata={title:"Privacy requests"};export const dynamic="force-dynamic";
export default async function PrivacyRequestsPage(){await requireAdmin();const supabase=await createClient();const {data:requests}=await supabase.from("data_subject_requests").select("id,kind,status,requested_at,acknowledged_at,users!data_subject_requests_user_id_fkey(email,display_name)").in("status",["pending","processing"]).order("requested_at");return <AdminFrame><div className={s.navSpace}/><div className="dashboard-heading"><div><span className="eyebrow">Data rights</span><h1>Privacy requests</h1></div><span className="badge badge-warning">{requests?.length||0} active</span></div>{requests?.length?<div className={s.queue}>{requests.map((request)=>{const user=Array.isArray(request.users)?request.users[0]:request.users;return <article className={s.item} key={request.id}><div><h2>{request.kind} request</h2><p>{user?.display_name||"Unnamed"} · {user?.email}</p></div><div className={s.meta}><strong>{request.status}</strong><small>Requested {new Date(request.requested_at).toLocaleString("en")}</small></div><div className={s.actions}><form action={reviewDataRequest}><input type="hidden" name="id" value={request.id}/><select name="status" defaultValue={request.status==="pending"?"processing":"completed"}><option value="processing">Start processing</option><option value="completed">Mark completed</option><option value="rejected">Reject</option></select><input name="reason" placeholder="Required if rejected"/><button className="button button-primary">Update</button></form></div></article>})}</div>:<div className={s.empty}>No active privacy requests.</div>}</AdminFrame>}
