import type { Metadata } from "next";
import { resolveReport } from "@/app/actions/admin-operations";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { AdminFrame } from "@/components/admin-frame";
import s from "../admin.module.css";

export const metadata: Metadata={title:"Reports"}; export const dynamic="force-dynamic";
export default async function ReportsPage(){await requireAdmin();const supabase=await createClient();const {data:reports}=await supabase.from("reports").select("id,reason,details,status,created_at,duel_id,vendor_organization_id,users!reports_reporter_user_id_fkey(email)").in("status",["open","investigating"]).order("created_at");return <AdminFrame><div className={s.navSpace}/><div className="dashboard-heading"><div><span className="eyebrow">Safety queue</span><h1>User reports</h1></div><span className="badge badge-warning">{reports?.length||0} open</span></div>{reports?.length?<div className={s.queue}>{reports.map((report)=>{const user=Array.isArray(report.users)?report.users[0]:report.users;return <article className={s.item} key={report.id}><div><h2>{report.reason}</h2><p>{report.details||"No additional details"}</p></div><div className={s.meta}><strong>{report.status}</strong><small>By {user?.email||"Unknown"} · {new Date(report.created_at).toLocaleString("en")}</small><small>Target {report.duel_id?`Duel ${report.duel_id}`:`Vendor ${report.vendor_organization_id}`}</small></div><div className={s.actions}><form action={resolveReport}><input type="hidden" name="id" value={report.id}/><select name="status" defaultValue="investigating"><option value="investigating">Investigate</option><option value="resolved">Resolve</option><option value="dismissed">Dismiss</option></select><input name="reason" placeholder="Operator note"/><button className="button button-primary">Update</button></form></div></article>})}</div>:<div className={s.empty}>No open reports.</div>}</AdminFrame>}
