"use client";
import { useEffect,useState } from "react";

type SavedField={value:string;checked?:boolean};
export function FormRecovery({formId,storageKey,exclude=""}:{formId:string;storageKey:string;exclude?:string}){
  const [saved,setSaved]=useState(false);
  useEffect(()=>{const form=document.getElementById(formId) as HTMLFormElement|null;if(!form)return;const key=`vendorduel:form:${storageKey}`;let submitting=false;const excluded=new Set(exclude.split(",").filter(Boolean));
    try{const raw=sessionStorage.getItem(key);if(raw){const data=JSON.parse(raw) as Record<string,SavedField>;for(const element of Array.from(form.elements)){if(!(element instanceof HTMLInputElement||element instanceof HTMLTextAreaElement||element instanceof HTMLSelectElement)||!element.name||excluded.has(element.name))continue;const entry=data[element.name];if(!entry)continue;if(element instanceof HTMLInputElement&&(element.type==="checkbox"||element.type==="radio")){element.checked=Boolean(entry.checked)}else if(!element.value){element.value=entry.value}element.dispatchEvent(new Event("change",{bubbles:true}))}queueMicrotask(()=>setSaved(true))}}catch{sessionStorage.removeItem(key)}
    let timer:ReturnType<typeof setTimeout>;const persist=()=>{clearTimeout(timer);timer=setTimeout(()=>{const data:Record<string,SavedField>={};for(const element of Array.from(form.elements)){if(!(element instanceof HTMLInputElement||element instanceof HTMLTextAreaElement||element instanceof HTMLSelectElement)||!element.name||excluded.has(element.name)||element instanceof HTMLInputElement&&["file","hidden","submit","button","password"].includes(element.type))continue;data[element.name]={value:element.value,...(element instanceof HTMLInputElement&&(element.type==="checkbox"||element.type==="radio")?{checked:element.checked}:{})}}sessionStorage.setItem(key,JSON.stringify(data));setSaved(true)},250)};
    const onSubmit=()=>{submitting=true};const onPageHide=()=>{if(submitting)sessionStorage.removeItem(key)};form.addEventListener("input",persist);form.addEventListener("change",persist);form.addEventListener("submit",onSubmit);window.addEventListener("pagehide",onPageHide);return()=>{clearTimeout(timer);form.removeEventListener("input",persist);form.removeEventListener("change",persist);form.removeEventListener("submit",onSubmit);window.removeEventListener("pagehide",onPageHide)}} ,[formId,storageKey,exclude]);
  if(!saved)return null;return <button type="button" className="form-recovery-clear" onClick={()=>{sessionStorage.removeItem(`vendorduel:form:${storageKey}`);setSaved(false)}}>Clear recovered form</button>;
}
