import type { Metadata } from "next";
import { refundPayment } from "@/app/actions/admin-operations";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { AdminFrame } from "@/components/admin-frame";
import s from "../admin.module.css";

export const metadata: Metadata={title:"Payments and refunds"}; export const dynamic="force-dynamic";
export default async function PaymentsPage(){await requireAdmin();const supabase=await createClient();const {data:payments}=await supabase.from("payments").select("id,amount,currency,status,provider_payment_intent_id,provider_receipt_url,paid_at,refunded_at,created_at,vendor_organization_id").order("created_at",{ascending:false}).limit(100);return <AdminFrame><div className={s.navSpace}/><div className="dashboard-heading"><div><span className="eyebrow">Revenue operations</span><h1>Payments & refunds</h1></div><span className="badge">Latest 100</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Created</th><th>Payment</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments?.map((payment)=><tr key={payment.id}><td>{new Date(payment.created_at).toLocaleString("en")}</td><td><span className={s.code}>{payment.provider_payment_intent_id||payment.id}</span></td><td><span className={s.code}>{payment.vendor_organization_id}</span></td><td>{new Intl.NumberFormat("en",{style:"currency",currency:payment.currency.toUpperCase()}).format(payment.amount/100)}</td><td><span className={`badge badge-${payment.status}`}>{payment.status}</span></td><td>{payment.status==="paid"?<form className={s.actions} action={refundPayment}><input type="hidden" name="id" value={payment.id}/><input name="reason" required minLength={3} placeholder="Refund reason"/><button className="button button-secondary">Refund</button></form>:payment.provider_receipt_url?<a className="text-link" href={payment.provider_receipt_url} target="_blank" rel="noreferrer">Receipt</a>:"—"}</td></tr>)}</tbody></table></div></AdminFrame>}
