import type { Metadata } from "next";
import { refundPayment } from "@/app/actions/admin-operations";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { AdminFrame } from "@/components/admin-frame";
import { AdminPager, pageRange } from "@/components/admin-pager";
import s from "../admin.module.css";

export const metadata: Metadata={title:"Payments and refunds"}; export const dynamic="force-dynamic";
export default async function PaymentsPage({searchParams}:{searchParams:Promise<{page?:string}>}){await requireAdmin();const supabase=await createClient();const {page,from,to,size}=pageRange((await searchParams).page,50);const {data:payments}=await supabase.from("payments").select("id,amount,currency,status,provider_payment_intent_id,provider_receipt_url,provider_refund_id,refund_initiated_at,paid_at,refunded_at,created_at,vendor_organization_id").order("created_at",{ascending:false}).range(from,to);const hasNext=(payments?.length??0)===size;return <AdminFrame><div className={s.navSpace}/><div className="dashboard-heading"><div><span className="eyebrow">Revenue operations</span><h1>Payments & refunds</h1></div><span className="badge">Page {page}</span></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Created</th><th>Payment</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Reconciliation</th><th>Action</th></tr></thead><tbody>{payments?.map((payment)=><tr key={payment.id}><td>{new Date(payment.created_at).toLocaleString("en")}</td><td><span className={s.code}>{payment.provider_payment_intent_id||payment.id}</span></td><td><span className={s.code}>{payment.vendor_organization_id}</span></td><td>{new Intl.NumberFormat("en",{style:"currency",currency:payment.currency.toUpperCase()}).format(payment.amount/100)}</td><td><span className={`badge badge-${payment.status}`}>{payment.status}</span></td><td>{payment.status==="refunded"?<span title={payment.provider_refund_id||undefined}>Refunded{payment.refunded_at?` · ${new Date(payment.refunded_at).toLocaleDateString("en")}`:""}</span>:payment.refund_initiated_at?<span className="badge badge-warning">Refund pending</span>:"—"}</td><td>{payment.status==="paid"?<form className={s.actions} action={refundPayment}><input type="hidden" name="id" value={payment.id}/><input name="reason" required minLength={3} placeholder="Refund reason"/><button className="button button-secondary">Refund</button></form>:payment.provider_receipt_url?<a className="text-link" href={payment.provider_receipt_url} target="_blank" rel="noreferrer">Receipt</a>:"—"}</td></tr>)}</tbody></table></div><AdminPager basePath="/admin/payments" page={page} hasNext={hasNext}/></AdminFrame>}
